/** Plain-language UI copy — technical terms kept, jargon explained inline. */

export const UI = {
  brand: {
    name: 'Bogie Flow',
    tagline: 'Track-bed monitoring',
  },
  nav: {
    overview: 'Overview',
    analysis: 'Analysis',
    maintenance: 'Maintenance',
    climate: 'Climate',
    scan: 'Run corridor scan',
    scanHint: 'Triggers a monsoon stress test on segment S4',
    linkActive: 'Live data connected',
    linkReconnecting: (n) => (n > 0 ? `Reconnecting (${n})…` : 'Reconnecting to server…'),
  },
  topbar: {
    connected: 'Connected',
    reconnecting: (n) => (n > 0 ? `Reconnecting (${n})…` : 'Reconnecting'),
    tickets: (n) => `${n} open ticket${n !== 1 ? 's' : ''}`,
  },
  footer: {
    uptime: 'Uptime',
    agent: 'AI agent',
    agentOk: 'Running normally',
    agentReconnecting: 'Reconnecting',
    segment: 'Train segment',
    stationMap: 'Station map',
    networkLogs: 'Network logs',
    sopDocs: 'Procedure docs',
  },
  corridor: {
    feedTitle: 'Corridor feed',
    feedSub: 'Live track view · 64-frame scrub',
    scrubHint: 'Scroll the page to move along the corridor · Hold Shift and wheel on the image to scrub frames · Drag the bar below',
    live: 'Live',
    scrubRailHint: 'Scroll page · Shift+wheel · drag bar',
  },
  status: {
    kicker: 'Corridor status',
    connecting: 'Connecting to corridor telemetry…',
    allNominal: (total) =>
      total > 0 ? `All ${total} segments nominal` : 'All segments nominal',
    operational: (total) => `${total}/${total} operational · no active warnings`,
    needsAttention: (count) =>
      count === 1 ? '1 segment needs attention' : `${count} segments need attention`,
    watchListLabel: 'Segments requiring attention',
  },
  briefing: {
    title: 'What to do next',
    sub: 'Priority plan from live telemetry',
    today: 'Today',
    train: 'Train location',
    watch: 'Highest-risk segment',
    tickets: 'Open tickets',
    p1: (n) => `${n} urgent (P1)`,
    planNominal: 'All six segments look normal. Keep routine corridor watch.',
    planP1: (n) =>
      `${n} urgent maintenance ticket${n > 1 ? 's' : ''} — check the maintenance queue first.`,
    planCritical: (id, label) =>
      `${id} needs attention (${label}). Open segment analysis before the next train pass.`,
    planTrain: (seg) =>
      `Train is at ${seg}. Watch vibration on the segments ahead.`,
    review: (id) => `Review ${id}`,
    maintenanceLog: 'Maintenance queue',
    stationMap: 'Station map',
  },
  segments: {
    stripStatus: {
      critical: 'CRITICAL',
      vibWarn: 'Vibration warning',
      op: (pct) => `Track health ${pct}%`,
    },
  },
  metrics: {
    peak: 'Peak vibration',
    peakTech: 'Peak amplitude (mm)',
    fatigue: 'Fatigue load (est.)',
    fatigueTech: 'Fatigue index (%, estimated)',
    bearing: 'Bearing heat (est.)',
    bearingTech: 'Bearing temperature (°C, estimated)',
  },
  analysis: {
    authorizeTitle: 'Run diagnostic inject',
    authorizeHint: 'Demo only: simulates a track fault on this segment and opens the maintenance queue',
    authorizeLabel: 'Run diagnostic inject',
    authorizeLoading: 'Injecting…',
    authorizeDone: 'Inject sent',
    authorizeFailed: 'Inject failed',
    segmentFocus: 'Selected segment',
    recommended: 'Recommended action',
    chartBars: 'Soil moisture (bars)',
    chartLine: 'Rainfall trend (line)',
    chartUnit: 'Relative intensity (0–1)',
  },
  maintenance: {
    emptyTitle: 'All clear — system nominal',
    emptySub: 'No open maintenance tickets. Agent logs continue below.',
  },
  climate: {
    moistureTitle: 'Soil moisture (average)',
    moistureTech: 'SOIL MOISTURE (AVG)',
    rainTitle: 'Rainfall (24 hours)',
    rainTech: 'PRECIPITATION / 24H',
    heatmapLegend: 'Measured rainfall intensity by segment (live telemetry)',
    measuredLabel: 'Measured (live)',
    estimatedLabel: 'Estimated (model-derived)',
  },
  simulation: {
    sectionLabel: 'Simulation / demo',
    title: 'Test scenarios',
    sub: 'Demo-only controls — inject simulated events, not live field actuators',
    apiReady: 'Backend ready',
    apiOffline: 'Offline',
    monsoon: 'Heavy rain · S4',
    monsoonHint: 'Simulates monsoon on segment S4 (rain + soil saturation)',
    anomaly: 'Track fault · S4',
    anomalyHint: 'Injects a vibration anomaly on segment S4',
    stress: (seg) => `Stress test · ${seg}`,
    stressHint: 'Applies monsoon-level stress on the train’s current segment',
    climateLink: 'Open climate view',
    sent: 'Scenario sent to simulation',
    offline: 'Backend unavailable — start the Python server',
  },
  anomaly: {
    title: 'Live alerts',
    empty: 'No anomalies right now',
  },
  guide: {
    welcome:
      'Hi — I can walk you through the dashboard or answer questions about segments, scrubbing, tickets, and simulations. Try a quick topic or start the guided tour.',
    fabLabel: 'Open corridor guide',
    launcherKicker: 'Corridor help',
    launcherTitle: 'How do you want help?',
    launcherTourLabel: 'Page walkthrough',
    launcherTourDesc: 'Step through Overview, Analysis, Maintenance, and Climate with highlights.',
    launcherChatLabel: 'Corridor chat',
    launcherChatDesc: 'Ask about segments, tickets, scrubbing, and demo injects.',
    launcherDefaultTag: 'Default',
    title: 'Corridor guide',
    subtitle: 'Ask questions about the dashboard',
    placeholder: 'Ask about segments, scrubbing, tickets…',
    startTour: 'Start guided tour',
    next: 'Next step',
    back: 'Back',
    skip: 'Skip tour',
    finish: 'Finish',
    askAi: 'Ask AI',
    aiUnavailable:
      'AI is off — using built-in answers. Add GUIDE_AI_API_KEY to `.env` in the project root for Gemini.',
    quickTopics: ['How do I scrub the corridor?', 'What is P1?', 'Explain segments S1–S6', 'Simulation inject'],
  },
}
